--
-- PostgreSQL database dump
--

\restrict d7FKXbJLEhDsaeL4pxV4U2VI20cMmxpOCTASMCe66znFwwqVuR5XAEqy8HKIdbv

-- Dumped from database version 15.14
-- Dumped by pg_dump version 15.14

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_app_invoice; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_app_invoice (
    id bigint NOT NULL,
    invoice_number integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    order_id integer NOT NULL,
    CONSTRAINT auth_app_invoice_invoice_number_check CHECK ((invoice_number >= 0))
);


ALTER TABLE public.auth_app_invoice OWNER TO postgres;

--
-- Name: auth_app_invoice_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_app_invoice ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_app_invoice_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO admin;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO admin;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO admin;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO admin;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO admin;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO admin;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: clients; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.clients (
    client_id integer NOT NULL,
    client_name text NOT NULL,
    client_phone text,
    client_email text,
    client_address text,
    loyalty_lvl text,
    registration_date date
);


ALTER TABLE public.clients OWNER TO admin;

--
-- Name: clients_client_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.clients ALTER COLUMN client_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clients_client_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO admin;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO admin;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO admin;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO admin;

--
-- Name: order_items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.order_items (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    order_id integer NOT NULL,
    product_id integer NOT NULL,
    CONSTRAINT order_items_quantity_check CHECK ((quantity >= 0))
);


ALTER TABLE public.order_items OWNER TO postgres;

--
-- Name: order_items_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.order_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.orders (
    order_id integer NOT NULL,
    client_id integer,
    order_total real,
    delivery_company text,
    order_status text,
    order_date date
);


ALTER TABLE public.orders OWNER TO admin;

--
-- Name: product_storage; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.product_storage (
    product_id integer NOT NULL,
    warehouse_id integer NOT NULL,
    amount integer,
    presence boolean
);


ALTER TABLE public.product_storage OWNER TO admin;

--
-- Name: products; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.products (
    product_id integer NOT NULL,
    product_name text NOT NULL,
    product_price real NOT NULL,
    product_material text,
    supplier_id integer,
    product_weight real,
    product_color text,
    date_added date
);


ALTER TABLE public.products OWNER TO admin;

--
-- Name: suppliers; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.suppliers (
    supplier_id integer NOT NULL,
    name text NOT NULL
);


ALTER TABLE public.suppliers OWNER TO admin;

--
-- Name: warehouses; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.warehouses (
    warehouse_id integer NOT NULL,
    warehouse_address text,
    warehouse_phone text,
    warehouse_lead text
);


ALTER TABLE public.warehouses OWNER TO admin;

--
-- Data for Name: auth_app_invoice; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_app_invoice (id, invoice_number, created_at, order_id) FROM stdin;
1	1	2025-11-29 07:46:56.630011+03	2
2	2	2025-11-29 07:47:18.8611+03	1
21	3	2025-11-29 08:38:10.213925+03	3
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add auth group	8	add_authgroup
26	Can change auth group	8	change_authgroup
27	Can delete auth group	8	delete_authgroup
28	Can view auth group	8	view_authgroup
29	Can add auth group permissions	9	add_authgrouppermissions
30	Can change auth group permissions	9	change_authgrouppermissions
31	Can delete auth group permissions	9	delete_authgrouppermissions
32	Can view auth group permissions	9	view_authgrouppermissions
33	Can add auth permission	10	add_authpermission
34	Can change auth permission	10	change_authpermission
35	Can delete auth permission	10	delete_authpermission
36	Can view auth permission	10	view_authpermission
37	Can add auth user	11	add_authuser
38	Can change auth user	11	change_authuser
39	Can delete auth user	11	delete_authuser
40	Can view auth user	11	view_authuser
41	Can add auth user groups	12	add_authusergroups
42	Can change auth user groups	12	change_authusergroups
43	Can delete auth user groups	12	delete_authusergroups
44	Can view auth user groups	12	view_authusergroups
45	Can add auth user user permissions	13	add_authuseruserpermissions
46	Can change auth user user permissions	13	change_authuseruserpermissions
47	Can delete auth user user permissions	13	delete_authuseruserpermissions
48	Can view auth user user permissions	13	view_authuseruserpermissions
49	Can add clients	14	add_clients
50	Can change clients	14	change_clients
51	Can delete clients	14	delete_clients
52	Can view clients	14	view_clients
53	Can add django admin log	15	add_djangoadminlog
54	Can change django admin log	15	change_djangoadminlog
55	Can delete django admin log	15	delete_djangoadminlog
56	Can view django admin log	15	view_djangoadminlog
57	Can add django content type	16	add_djangocontenttype
58	Can change django content type	16	change_djangocontenttype
59	Can delete django content type	16	delete_djangocontenttype
60	Can view django content type	16	view_djangocontenttype
61	Can add django migrations	17	add_djangomigrations
62	Can change django migrations	17	change_djangomigrations
63	Can delete django migrations	17	delete_djangomigrations
64	Can view django migrations	17	view_djangomigrations
65	Can add django session	18	add_djangosession
66	Can change django session	18	change_djangosession
67	Can delete django session	18	delete_djangosession
68	Can view django session	18	view_djangosession
69	Can add orders	7	add_orders
70	Can change orders	7	change_orders
71	Can delete orders	7	delete_orders
72	Can view orders	7	view_orders
73	Can add product lists	19	add_productlists
74	Can change product lists	19	change_productlists
75	Can delete product lists	19	delete_productlists
76	Can view product lists	19	view_productlists
77	Can add products	20	add_products
78	Can change products	20	change_products
79	Can delete products	20	delete_products
80	Can view products	20	view_products
81	Can add product storage	21	add_productstorage
82	Can change product storage	21	change_productstorage
83	Can delete product storage	21	delete_productstorage
84	Can view product storage	21	view_productstorage
85	Can add suppliers	22	add_suppliers
86	Can change suppliers	22	change_suppliers
87	Can delete suppliers	22	delete_suppliers
88	Can view suppliers	22	view_suppliers
89	Can add warehouses	23	add_warehouses
90	Can change warehouses	23	change_warehouses
91	Can delete warehouses	23	delete_warehouses
92	Can view warehouses	23	view_warehouses
93	Can add order item	24	add_orderitem
94	Can change order item	24	change_orderitem
95	Can delete order item	24	delete_orderitem
96	Can view order item	24	view_orderitem
97	Can add Накладная	25	add_invoice
98	Can change Накладная	25	change_invoice
99	Can delete Накладная	25	delete_invoice
100	Can view Накладная	25	view_invoice
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$1000000$jCOsG22wB7WKTn5piU2FUM$IpJWTN53iwyEpNsAjXpD54qXMsI/BhQpyBrRZF/ojxs=	2025-11-06 01:51:05.032231+03	t	maxparh				t	t	2025-11-06 01:49:10.243893+03
2	pbkdf2_sha256$1000000$z01Ba5Eek8kubh7pGzGUBG$ETTO8Vrpf399rhgx5bBiMmDjm5Yk5zHRscWfpo36S2Y=	2025-11-29 15:30:20.235222+03	t	admin				t	t	2025-11-06 16:36:13.189456+03
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: clients; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.clients (client_id, client_name, client_phone, client_email, client_address, loyalty_lvl, registration_date) FROM stdin;
81	Иван Петров	+7 901 123-45-67	ivan.petrov@example.com	Москва, ул. Тверская, д. 14, кв. 52	Стандартный	2025-10-15
82	Мария Соколова	+7 915 842-11-29	maria.sokolova@example.com	Санкт-Петербург, пр. Невский, д. 88, кв. 17	Премиум	2025-11-12
83	Алексей Иванов	+7 903 557-89-04	alexey.ivanov@example.com	Казань, ул. Баумана, д. 7, кв. 41	Платинум	2025-11-13
84	Елена Кузнецова	+7 916 774-33-10	elena.kuznetsova@example.com	Екатеринбург, ул. Малышева, д. 120, кв. 9	Стандартный	2025-11-21
85	Дмитрий Орлов	+7 925 690-12-55	d.orlov@example.com	Новосибирск, ул. Ленина, д. 22, кв. 63	Стандартный	2025-09-16
87	Сергиенко Александр	+7 903 554-84-03	sergeinko.alex@gmail.com	Москва, ул. Вавилова, д. 14, кв. 32	Стандартный	2025-11-03
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2025-11-06 16:31:27.664142+03	1	Orders object (1)	1	[{"added": {}}]	7	1
2	2025-11-06 16:31:29.742529+03	1	Orders object (1)	2	[]	7	1
3	2025-11-06 16:37:31.379043+03	2	Orders object (2)	1	[{"added": {}}]	7	2
4	2025-11-09 00:27:28.749075+03	2	Clients object (2)	3		14	2
5	2025-11-09 00:27:33.78976+03	1	Clients object (1)	3		14	2
6	2025-11-09 00:30:21.729739+03	3	Clients object (3)	3		14	2
7	2025-11-09 00:30:26.448348+03	4	Clients object (4)	3		14	2
8	2025-11-09 19:26:48.901312+03	12	Clients object (12)	3		14	2
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	auth_app	orders
8	auth_app	authgroup
9	auth_app	authgrouppermissions
10	auth_app	authpermission
11	auth_app	authuser
12	auth_app	authusergroups
13	auth_app	authuseruserpermissions
14	auth_app	clients
15	auth_app	djangoadminlog
16	auth_app	djangocontenttype
17	auth_app	djangomigrations
18	auth_app	djangosession
19	auth_app	productlists
20	auth_app	products
21	auth_app	productstorage
22	auth_app	suppliers
23	auth_app	warehouses
24	auth_app	orderitem
25	auth_app	invoice
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-11-06 01:39:14.423641+03
2	auth	0001_initial	2025-11-06 01:39:14.496874+03
3	admin	0001_initial	2025-11-06 01:39:14.518261+03
4	admin	0002_logentry_remove_auto_add	2025-11-06 01:39:14.524644+03
5	admin	0003_logentry_add_action_flag_choices	2025-11-06 01:39:14.531874+03
6	contenttypes	0002_remove_content_type_name	2025-11-06 01:39:14.548842+03
7	auth	0002_alter_permission_name_max_length	2025-11-06 01:39:14.557479+03
8	auth	0003_alter_user_email_max_length	2025-11-06 01:39:14.565233+03
9	auth	0004_alter_user_username_opts	2025-11-06 01:39:14.571999+03
10	auth	0005_alter_user_last_login_null	2025-11-06 01:39:14.581392+03
11	auth	0006_require_contenttypes_0002	2025-11-06 01:39:14.583106+03
12	auth	0007_alter_validators_add_error_messages	2025-11-06 01:39:14.58972+03
13	auth	0008_alter_user_username_max_length	2025-11-06 01:39:14.601869+03
14	auth	0009_alter_user_last_name_max_length	2025-11-06 01:39:14.61005+03
15	auth	0010_alter_group_name_max_length	2025-11-06 01:39:14.620046+03
16	auth	0011_update_proxy_permissions	2025-11-06 01:39:14.626917+03
17	auth	0012_alter_user_first_name_max_length	2025-11-06 01:39:14.636533+03
18	sessions	0001_initial	2025-11-06 01:39:14.649601+03
19	auth_app	0001_initial	2025-11-08 22:17:16.555974+03
20	auth_app	0002_alter_clients_options	2025-11-09 00:14:32.011027+03
21	auth_app	0003_alter_clients_client_id	2025-11-09 00:15:15.387732+03
22	auth_app	0004_alter_orders_options_alter_productlists_options_and_more	2025-11-09 00:27:00.671583+03
23	auth_app	0002_orderitem_delete_authgroup_and_more	2025-11-29 00:22:34.230471+03
24	auth_app	0002_add_invoice_table	2025-11-29 07:33:10.849492+03
25	auth_app	0003_rename_invoice_table	2025-11-29 07:35:56.447789+03
26	auth_app	0004_alter_invoice_order_alter_invoice_table	2025-11-29 08:33:54.61168+03
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
1qtux8te7x4jlnholdrk1wnddcjxpsef	.eJxVjDsOwjAQBe_iGlnrD_5Q0nMGy7tecADZUpxUiLtDpBTQvpl5L5HyutS0Dp7TVMRJaHH43TDTg9sGyj23W5fU2zJPKDdF7nTISy_8PO_u30HNo37rmOFoEK2CCMSaAbR3RgUfbSELrBVFzwYDeYWAmq8-KnDssICFoMX7A8D2Nvo:1vH0AH:FKHNfktxlF4zW7wch6N3GMtqkoHc9shD9Y-O2o7-U1k	2025-11-20 16:36:37.776228+03
\.


--
-- Data for Name: order_items; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.order_items (id, quantity, order_id, product_id) FROM stdin;
13	1	1	6
14	2	1	12
15	1	2	6
16	1	3	8
17	1	3	12
18	1	3	13
23	1	4	13
24	1	4	12
25	1	4	6
\.


--
-- Data for Name: orders; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.orders (order_id, client_id, order_total, delivery_company, order_status, order_date) FROM stdin;
2	84	620000	DHL	В обработке	2025-11-04
3	87	1.92e+06	СДЭК	Выполняется	2025-11-14
1	83	2.4e+06	СДЭК	Выполняется	2025-11-15
4	85	1.92e+06	СДЭК	В обработке	2025-11-05
\.


--
-- Data for Name: product_storage; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.product_storage (product_id, warehouse_id, amount, presence) FROM stdin;
\.


--
-- Data for Name: products; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.products (product_id, product_name, product_price, product_material, supplier_id, product_weight, product_color, date_added) FROM stdin;
1	Кресло-лонджер «Monte Carlo»	285000	Натуральная кожа full-grain, массив ореха, латунная фурнитура	3	24	Тёмно-бордовый	2025-09-12
2	Кресло-лонджер «Monte Carlo»	285000	Натуральная кожа full-grain, массив ореха, латунная фурнитура	3	24	Тёмно-зеленый	2025-09-12
3	Кресло-лонджер «Monte Carlo»	285000	Натуральная кожа full-grain, массив ореха, латунная фурнитура	3	24	Чёрный графит	2025-09-12
4	Кресло-лонджер «Monte Carlo»	285000	Натуральная кожа full-grain, массив ореха, латунная фурнитура	3	24	Венге	2025-09-12
5	Обеденный стол «Venere»	620000	Мрамор Calacatta Viola, основание из полированной нержавеющей стали	6	142	Фиолетово-белый мрамор	2025-09-17
6	Обеденный стол «Venere»	620000	Мрамор Calacatta Viola, основание из полированной нержавеющей стали	6	142	Чёрный Marquina мрамор	2025-09-17
7	Обеденный стол «Venere»	620000	Мрамор Calacatta Viola, основание из полированной нержавеющей стали	6	142	Серебристый мрамор	2025-09-17
8	Обеденный стол «Venere»	620000	Мрамор Calacatta Viola, основание из полированной нержавеющей стали	6	142	Пепельный мрамор	2025-09-17
9	Название: Кровать «Aether»	890000	Массив дуба ручной сушки, ткань velvet (состав: шёлк + хлопок), ручная стёжка	1	185	Слоновая кость	2025-08-21
10	Название: Кровать «Aether»	890000	Массив дуба ручной сушки, ткань velvet (состав: шёлк + хлопок), ручная стёжка	1	185	Индиго	2025-08-21
11	Название: Кровать «Aether»	890000	Массив дуба ручной сушки, ткань velvet (состав: шёлк + хлопок), ручная стёжка	1	185	Норвежский лес	2025-08-21
12	Название: Кровать «Aether»	890000	Массив дуба ручной сушки, ткань velvet (состав: шёлк + хлопок), ручная стёжка	1	185	Бамбуковая долина	2025-08-21
13	Книжный шкаф «Bibliotheca Maxima»	410000	Массив вишни, стекло с антибликовым покрытием, внутренняя подсветка LED (регулируемая)	5	98	Вишнёвный	2025-10-27
\.


--
-- Data for Name: suppliers; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.suppliers (supplier_id, name) FROM stdin;
1	МебельГранд
2	КомфортТрейд
3	ЭкоМебель Поставка
4	УютПром
5	ИнтерьерПоставка+
6	Мебельторг Север
7	Тест
\.


--
-- Data for Name: warehouses; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.warehouses (warehouse_id, warehouse_address, warehouse_phone, warehouse_lead) FROM stdin;
1	г. Москва, ул. Ленинская, д. 42, стр. 3	+7 (495) 123-45-67	Иванов Сергей Петрович  
2	г. Санкт-Петербург, пр. Обуховской Обороны, д. 120	+7 (812) 987-65-43	Петрова Анна Викторовна  
3	г. Екатеринбург, ул. Чапаева, д. 88	+7 (343) 555-01-99	Смирнов Дмитрий Александрович  
4	г. Новосибирск, ул. Фрунзе, д. 215	+7 (383) 246-80-24	Козлова Елена Игоревна
\.


--
-- Name: auth_app_invoice_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_app_invoice_id_seq', 21, true);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 100, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 2, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: clients_client_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.clients_client_id_seq', 89, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 8, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 25, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 26, true);


--
-- Name: order_items_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.order_items_id_seq', 58, true);


--
-- Name: auth_app_invoice auth_app_invoice_invoice_number_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_app_invoice
    ADD CONSTRAINT auth_app_invoice_invoice_number_key UNIQUE (invoice_number);


--
-- Name: auth_app_invoice auth_app_invoice_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_app_invoice
    ADD CONSTRAINT auth_app_invoice_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: clients clients_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT clients_pkey PRIMARY KEY (client_id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: auth_app_invoice invoice_order_id_64391c2e_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_app_invoice
    ADD CONSTRAINT invoice_order_id_64391c2e_uniq UNIQUE (order_id);


--
-- Name: order_items order_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_pkey PRIMARY KEY (id);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (order_id);


--
-- Name: product_storage product_storage_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.product_storage
    ADD CONSTRAINT product_storage_pkey PRIMARY KEY (product_id, warehouse_id);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (product_id);


--
-- Name: suppliers suppliers_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.suppliers
    ADD CONSTRAINT suppliers_pkey PRIMARY KEY (supplier_id);


--
-- Name: warehouses warehouses_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.warehouses
    ADD CONSTRAINT warehouses_pkey PRIMARY KEY (warehouse_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: order_items_order_id_412ad78b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX order_items_order_id_412ad78b ON public.order_items USING btree (order_id);


--
-- Name: order_items_product_id_dd557d5a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX order_items_product_id_dd557d5a ON public.order_items USING btree (product_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_app_invoice invoice_order_id_64391c2e_fk_orders_order_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_app_invoice
    ADD CONSTRAINT invoice_order_id_64391c2e_fk_orders_order_id FOREIGN KEY (order_id) REFERENCES public.orders(order_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: order_items order_items_order_id_412ad78b_fk_orders_order_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_order_id_412ad78b_fk_orders_order_id FOREIGN KEY (order_id) REFERENCES public.orders(order_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: order_items order_items_product_id_dd557d5a_fk_products_product_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_product_id_dd557d5a_fk_products_product_id FOREIGN KEY (product_id) REFERENCES public.products(product_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders orders_client_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(client_id);


--
-- Name: product_storage product_storage_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.product_storage
    ADD CONSTRAINT product_storage_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(product_id);


--
-- Name: product_storage product_storage_warehouse_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.product_storage
    ADD CONSTRAINT product_storage_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES public.warehouses(warehouse_id);


--
-- Name: products products_supplier_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(supplier_id);


--
-- PostgreSQL database dump complete
--

\unrestrict d7FKXbJLEhDsaeL4pxV4U2VI20cMmxpOCTASMCe66znFwwqVuR5XAEqy8HKIdbv

