# Generated by Django 5.2.7 on 2025-11-29 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.TextField()),
                ('client_phone', models.TextField(blank=True, null=True)),
                ('client_email', models.TextField(blank=True, null=True)),
                ('client_address', models.TextField(blank=True, null=True)),
                ('loyalty_lvl', models.TextField(blank=True, null=True)),
                ('registration_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.TextField()),
                ('product_price', models.FloatField()),
                ('product_material', models.TextField(blank=True, null=True)),
                ('product_weight', models.FloatField(blank=True, null=True)),
                ('product_color', models.TextField(blank=True, null=True)),
                ('date_added', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('supplier_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'suppliers',
            },
        ),
        migrations.CreateModel(
            name='Warehouses',
            fields=[
                ('warehouse_id', models.IntegerField(primary_key=True, serialize=False)),
                ('warehouse_address', models.TextField(blank=True, null=True)),
                ('warehouse_phone', models.TextField(blank=True, null=True)),
                ('warehouse_lead', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'warehouses',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_total', models.FloatField(blank=True, null=True)),
                ('delivery_company', models.TextField(blank=True, null=True)),
                ('order_status', models.TextField(blank=True, null=True)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_app.clients')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.PositiveIntegerField(editable=False, unique=True, verbose_name='Номер накладной')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.orders', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Накладная',
                'verbose_name_plural': 'Накладные',
                'ordering': ['-invoice_number'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='auth_app.orders')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth_app.products')),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auth_app.suppliers'),
        ),
        migrations.CreateModel(
            name='ProductStorage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('presence', models.BooleanField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.products')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.warehouses')),
            ],
            options={
                'db_table': 'product_storage',
                'unique_together': {('product', 'warehouse')},
            },
        ),
    ]
