# Generated by Django 5.2.7 on 2025-11-29 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_add_invoice_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.PositiveIntegerField(editable=False, unique=True, verbose_name='Номер накладной'),
        ),
        migrations.AlterModelTable(
            name='invoice',
            table='invoice',
        ),
    ]
