# Generated by Django 5.2.7 on 2025-11-29 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_rename_invoice_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.orders', unique=True, verbose_name='Заказ'),
        ),
        migrations.AlterModelTable(
            name='invoice',
            table=None,
        ),
    ]
